# [ENVIRONMENT: GitHub Actions | Repo: Watchtower-SwayZone.github.io]
# [SECURITY_TIER: Tier 1 Read-Only]

on:
  push:
    branches: [ "main" ]

# ENFORCE LEAST PRIVILEGE
permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
